### ISSUE TITLE
PILCO

### ISSUE THREAD

**Issue by iamWHTWD** [Haas11/I-PILCO#1]
Hello, I want to ask about PILCO, but I have been concerned about your GitHub, but I haven't found any specific contents. Do you want to ask if it's still in the process of writing? It's not easy to share, thank you for your reply

**Comment by vanusy** [comment]
Hello, this function is not correct.
When I run I-PILCO-master/Impedance_Control.m, the function work not well
[mu0, S0, xe_des, dxe_des, ddxe_des, T, Hf]...
    = genTrajectory(robot, peg, T0, T11, xhole, xc, T, dt);  
while it is defined in I-PILCO/util/genTrajectory.m as 
function [mu0, S0, xe_des, dxe_des, ddxe_des, Hf, Rd, Hd] = genTrajectory(robot, mode, H0, H1, H2, H3, xhole, xc, T, dt)

So, what's the problem?

**Comment by Haas11** [comment]
> Hello, I want to ask about PILCO, but I have been concerned about your GitHub, but I haven't found any specific contents. Do you want to ask if it's still in the process of writing? It's not easy to share, thank you for your reply

@iamWHTWD unfortunately this repository is no longer maintained.
It builds on the original PILCO algortihm which you can find at http://mlg.eng.cam.ac.uk/pilco/

@vanusy I presume you mean `\I-PILCO-master\Impedance_Control\ImpControl3Link.m` wihch indeed calls an old version of `util\genTrajectory.m`. genTrajectory now takes 4 homogeneous transform matrices.

This code is badly maintained and very application specific. I can not recommend using it.
